/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 114b4e7cc2936b8d8f848f67eb159d13)
interface __BaseEnv_Env {
	STATE: KVNamespace;
	CATALOG_URL: "https://catalog.s.download.windowsupdate.com/microsoftupdate/v6/wsusscan/wsusscn2.cab";
	GITHUB_API_URL: "https://api.github.com";
	GITHUB_OWNER: "potatoqualitee";
	GITHUB_REPO: "kbupdate";
	GITHUB_WORKFLOW: "refresh-kbupdate-library.yml";
	GITHUB_REF: "main";
	DISPATCH_ENABLED: "true";
	GITHUB_TOKEN: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "CATALOG_URL" | "GITHUB_API_URL" | "GITHUB_OWNER" | "GITHUB_REPO" | "GITHUB_WORKFLOW" | "GITHUB_REF" | "DISPATCH_ENABLED" | "GITHUB_TOKEN">> {}
}
