name: Windows test
on: [push]

jobs:
  build:
    name: Let's see what needs to be installed
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v1
      - name: Check for needed updates
        shell: powershell
        run: |
          Set-PSRepository -Name PSGallery -InstallationPolicy Trusted
          Install-Module PSFramework, kbupdate-library, PSSQLite
          Import-Module ./kbupdate.psd1 -ErrorAction Stop
          mkdir C:\temp
          $scanfile = Save-KbScanFile -Path C:\temp -AllowClobber
          Get-KbNeededUpdate -ScanFilePath $scanfile
